#!/usr/bin/env python3
"""Generate paper/generated/values.tex from the results ledger.

Resolves every entry in provenance/ledger.yaml against the distilled run records and
writes one `\\valdef{claim-key}{value}` line per entry. The paper cites a number as
`\\val{claim-key}` (macros defined in paper/main.tex), so the number physically comes
from the ledger and cannot be mistyped or drift as prose is edited.

values.tex is committed (a generated lockfile) so `latexmk` builds without running this
script; `scripts/check_grounding.py` guarantees it stays in sync. Resolution is
all-or-nothing: if ANY entry fails to resolve, nothing is written and the exit code is
nonzero, naming the offending claim-key.

Examples:
  python scripts/gen_values_tex.py
  python scripts/gen_values_tex.py --check-only   # resolve everything, write nothing
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import provenance_lib as pl  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parent.parent
HEADER = (
    "% Generated by scripts/gen_values_tex.py from provenance/ledger.yaml -- DO NOT EDIT.\n"
    "% Each line binds a claim-key to a value resolved from a distilled run record.\n"
    "% Cite in prose as \\val{claim-key}; regenerate after editing the ledger.\n"
)


def build_values_tex(entries, records):
    rendered = pl.render_all(entries, records)  # raises pl.ResolveError on any failure
    lines = [HEADER]
    for key in sorted(rendered):
        lines.append(f"\\valdef{{{key}}}{{{rendered[key]}}}\n")
    return "".join(lines)


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--ledger", default=str(REPO_ROOT / "provenance" / "ledger.yaml"))
    ap.add_argument("--runs", default=str(REPO_ROOT / "provenance" / "runs"))
    ap.add_argument("--out", default=str(REPO_ROOT / "paper" / "generated" / "values.tex"))
    ap.add_argument("--check-only", action="store_true",
                    help="Resolve all entries and report, but write nothing")
    args = ap.parse_args()

    entries = pl.load_ledger(args.ledger)
    records = pl.load_records(args.runs)
    try:
        content = build_values_tex(entries, records)
    except pl.ResolveError as e:
        print(f"ERROR resolving ledger: {e}", file=sys.stderr)
        return 1

    if args.check_only:
        print(f"resolved {len(entries)} ledger entries OK (no file written)")
        return 0

    out = Path(args.out)
    old = out.read_text() if out.exists() else None
    if old == content:
        print(f"{out} already up to date ({len(entries)} entries)")
        return 0
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(content)
    print(f"wrote {out} ({len(entries)} entries)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
